//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPrj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        internal int MusteriId;

        public int SiparisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public int MüsteriId { get; set; }
        public int UrunId { get; set; }
        public int Adet { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
